
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('games').del()
    .then(function () {
      // Inserts seed entries
      return knex('games').insert([
        {id: 1, playletters: 'airmega', validwords: {"validArr": [
          "aga",
          "agami",
          "agar",
          "age",
          "ager",
          "agma",
          "agria",
          "aia",
          "aiga",
          "aim",
          "aimer",
          "air",
          "ama",
          "ame",
          "ami",
          "amia",
          "amie",
          "amiga",
          "amir",
          "arame",
          "are",
          "area",
          "areg",
          "aria",
          "arm",
          "ear",
          "egma",
          "emir",
          "era",
          "erg",
          "erm",
          "gae",
          "gair",
          "gam",
          "gama",
          "game",
          "gamer",
          "gamier",
          "gar",
          "gare",
          "gari",
          "gear",
          "gem",
          "ger",
          "germ",
          "gie",
          "gram",
          "grama",
          "grame",
          "grim",
          "grime",
          "image",
          "imager",
          "ire",
          "maa",
          "maar",
          "maare",
          "mae",
          "mag",
          "mage",
          "magi",
          "maigre",
          "mair",
          "maire",
          "mar",
          "mara",
          "marae",
          "mare",
          "marg",
          "marge",
          "maria",
          "meg",
          "mega",
          "megara",
          "meri",
          "mig",
          "mir",
          "mirage",
          "mire",
          "rag",
          "raga",
          "rage",
          "ragi",
          "rai",
          "raia",
          "ram",
          "rami",
          "ramie",
          "ream",
          "reg",
          "regma",
          "rei",
          "rem",
          "ria",
          "riem",
          "rig",
          "rim",
          "rima",
          "rimae",
          "rime"
      ]}, perfectscore: null},
      ]);
    })
    .then(() => {
      // reset sequence
      return knex.raw(
        `SELECT setval('games_id_seq', (SELECT MAX(id) FROM games));`
      )
    })
};
